visualisation.cdeventsvisi.enabled=true
visualisation.cdeventsvisi.endpoint=http://cdevents-visi-127.0.0.1.nip.io/cdevents/visi
visualisation.grafanavisi.enabled=true
visualisation.grafanavisi.endpoint=http://localhost:8070/cdevents/visi
visualisation.dbstore.enabled=false
server.port=8099
