minio:
  enabled: true
backend:
  replicas: 1
read:
  replicas: 1
write:
  replicas: 1
loki:
  auth_enabled: false
  index_gateway:
    ring:
      replication_factor: 1
  commonConfig:
    replication_factor: 1
