apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdeventreciever-python
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: cdeventreciever-python
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: event-display
          image: cdeventreciever-python:latest
          imagePullPolicy: IfNotPresent

---

kind: Service
apiVersion: v1
metadata:
  name: cdeventreciever-python
  labels:
    app: cdeventreciever-python
spec:
  selector:
    app: cdeventreciever-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: cdeventrecieverport
